name: graphox
channels:
  - conda-forge
  - defaults
  - pyg
  - pytorch
dependencies:
  - pip
  - pandas
  - networkx
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - pyg
  - click
  - pot
  - networkit
  - seaborn
  - matplotlib
  - ignite
  - torch-scatter
  - click
  - pdoc3
